### PR TITLE
Extracted api dummy as new nginx service

### PR DESCRIPTION
**Pull request by stephenwf**
@giorgiosironi @lsh-0 @elrossco22

### CODE REVIEW

**Comment by giorgiosironi** [comment]
:+1: reusing part of the api-dummy-formula but tweaking it for this usage

**Comment by giorgiosironi** [comment]
Will enable the new states for EC2 instances only in `ci`.

**Comment by thewilkybarkid** [comment]
Rather than duplicate config etc, could we just make the port number a variable?

**Comment by giorgiosironi** [comment]
We can use a pillar for that.

**Comment by giorgiosironi** [comment]
The way to specify a pillar is like in `https://github.com/elifesciences/lax-formula/blob/master/salt/pillar/lax.sls`, but in https://github.com/elifesciences/search-formula/blob/master/salt/pillar/search.sls
Then you can refer to it with `{{ pillar.search.something }}` in jinja templates used with `file.managed`.

**Comment by stephenwf** [comment]
@giorgiosironi 
@thewilkybarkid 

Can I open a JIRA ticket for moving this to pillar and I'll pick it up later. I would like to unblock the set up for the E2E today.

**Comment by giorgiosironi** [comment]
Not a problem postponing for me, but also not a problem to go into `end2end` (apart from high WIP) since this affects only `ci`.

**Comment by giorgiosironi** [comment]
About setting it from search-formula: pillars are overridable too, so if you add a `api-dummy: ...` tree in `salt/pillar/search.sls` in `search-formula` you should be able to selectively override what comes from `salt/pillar/api-dummy.sls` in `api-dummy-formula`. As long as the pillars are included in the right order, and we'll make sure of that.

**Comment by stephenwf** [comment]
Just rebased, will merge now then

**Pull request merged**
