### PR TITLE
Added importing of content

### PR DESCRIPTION
**Pull request by stephenwf**
@giorgiosironi @lsh-0 

This will kick off the importing of content from the Dummy api. I've set this to only run on dev and CI. Is this the correct route to go?

This is still a WIP as the dummy-api needs to be spun up first

### CODE REVIEW

**Comment by giorgiosironi** [comment]
:+1: this is correct but I would move it to the end of the `init.sls` file for consistency.

**Comment by giorgiosironi** [comment]
The best choice for the api-dummy if you need it also in `ci` is to add it inside the EC2 instance itself, rather than rely on `api-dummy--ci` which may be turned off when you most need it. That would make it automatically available also for Vagrant VMs.

I would go for a separate `api-dummy.sls` file in this repo, then we can compose it with the `top.sls` depending on the environment:
- `example.top` used in Vagrant will have it
- `top.sls` inside the `builder-private` repository will have it only for `search--ci`

**Comment by stephenwf** [comment]
So would they share the PHP7 install? If I remember the dummy required GD library, but I guess if it can be wrapped up in conditionals it won't really matter.

Ill give that a go once I've got the ES versioning fixed.

**Comment by giorgiosironi** [comment]
They would share it so in those testing instances there will be additional PHP extensions to be used by `api-dummy`, true.

**Comment by stephenwf** [comment]
See #7

**Pull request closed without merging**
