### PR TITLE
Feature: fixes bug attempting to rotate elasticsearch log on follower

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by lsh-0** [comment]
uh oh, this doesn't look good:
```
[2019-05-07T04:24:57.574Z] [54.88.42.197] out: ----------
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:           ID: php-ppa
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:     Function: pkgrepo.managed
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:       Result: True
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:      Comment: Configured package repo 'php-ppa'
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:      Started: 04:22:24.452967
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:     Duration: 7776.569 ms
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:      Changes:   
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:               ----------
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:               repo:
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:                   ppa:ondrej/php
[2019-05-07T04:24:57.574Z] [54.88.42.197] out: ----------
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:           ID: php
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:     Function: pkg.installed
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:       Result: False
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:      Comment: Problem encountered installing package(s). Additional info follows:
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:               
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:               errors:
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:                   - E: Unable to locate package php7.0-gd
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:                     E: Couldn't find any package by regex 'php7.0-gd'
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:                     E: Unable to locate package php7.0-cli
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:                     E: Couldn't find any package by regex 'php7.0-cli'
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:                     E: Unable to locate package php7.0-mbstring
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:                     E: Couldn't find any package by regex 'php7.0-mbstring'
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:                     E: Unable to locate package php7.0-mcrypt
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:                     E: Couldn't find any package by regex 'php7.0-mcrypt'
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:                     E: Unable to locate package php7.0-xsl
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:                     E: Couldn't find any package by regex 'php7.0-xsl'
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:                     E: Unable to locate package php7.0-mysql
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:                     E: Couldn't find any package by regex 'php7.0-mysql'
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:                     E: Unable to locate package php7.0-curl
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:                     E: Couldn't find any package by regex 'php7.0-curl'
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:                     E: Unable to locate package php7.0-xml
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:                     E: Couldn't find any package by regex 'php7.0-xml'
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:      Started: 04:22:32.231829
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:     Duration: 355.357 ms
[2019-05-07T04:24:57.574Z] [54.88.42.197] out:      Changes:   
[2019-05-07T04:24:57.574Z] [54.88.42.197] out: ----------
```

investigating

**Comment by lsh-0** [comment]
I think 14.04 support has been dropped (can't blame him):

Screenshot at 2019-05-07 14-05-00

* https://launchpad.net/~ondrej/+archive/ubuntu/php/
* https://www.patreon.com/posts/ubuntu-14-04-php-22093917

I can't believe I didn't check his Patreon page for important updates. 

He has a bug tracker here actually that helped me hunt down the update:

* https://github.com/oerdnj/deb.sury.org

**Comment by giorgiosironi** [comment]
This escalates the priority to get on Ubuntu (16.04|18.04) and PHP 7.any for all PHP projects, if I understand correctly. We will be unable to build new virtual machines (hence to build also any separate formula change for these projects) until fixed.

**Comment by lsh-0** [comment]
ah - this is passing because the `pr-fresh-variant-follower-node` isn't running the smoke tests. The 18.04 upgrade will need to disable smoke tests on the follower node to get it to pass. I'll see if I can wrangle a condition so that particular node opts out.

this PR can actually be merged now I think.

**Comment by lsh-0** [comment]
build is green but I'm giving it a kick regardless. search-formula has seen some changes in the last week

**Comment by lsh-0** [comment]
failed here on `fresh` with a timeout restarting the gearman service:

```
[2019-09-09T03:12:09.120Z] [3.85.30.12] out: [0;31m----------[0;0m
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:     [0;31m      ID: gearman-configuration[0;0m
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:     [0;31mFunction: cmd.run[0;0m
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:     [0;31m    Name: systemctl stop gearman-job-server || stop gearman-job-server
[2019-09-09T03:12:09.120Z] [3.85.30.12] out: systemctl start gearman-job-server || start gearman-job-server
[2019-09-09T03:12:09.120Z] [3.85.30.12] out: [0;0m
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:     [0;31m  Result: False[0;0m
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:     [0;31m Comment: Command "systemctl stop gearman-job-server || stop gearman-job-server
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:               systemctl start gearman-job-server || start gearman-job-server
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:               " run[0;0m
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:     [0;31m Started: 03:09:18.242736[0;0m
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:     [0;31mDuration: 90146.167 ms[0;0m
[2019-09-09T03:12:09.120Z] [3.85.30.12] out: [0;31m     Changes:   
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:               [0;36m----------[0;0m
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:               [0;36mpid[0;0m:
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:                   [0;1;33m29907[0;0m
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:               [0;36mretcode[0;0m:
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:                   [0;1;33m127[0;0m
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:               [0;36mstderr[0;0m:
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:                   [0;32mJob for gearman-job-server.service failed because a timeout was exceeded.[0;0m
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:                   [0;32mSee "systemctl status gearman-job-server.service" and "journalctl -xe" for details.[0;0m
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:                   [0;32m/bin/bash: line 1: start: command not found[0;0m
[2019-09-09T03:12:09.120Z] [3.85.30.12] out:               [0;36mstdout[0;0m:[0;0m
[2019-09-09T03:12:09.120Z] [3.85.30.12] out: [0;31m----------[0;0m
```

removing the pre 18.04 parts of the formula is out of scope for this PR. kicking build, could just be one more gremlin

**Comment by lsh-0** [comment]
failed in same place again. I'll open another PR to clean that state up

**Comment by lsh-0** [comment]
depends on: https://github.com/elifesciences/search-formula/pull/39

**Pull request merged**
